site_name: Rick (Ruiqi) Ding
theme: material
#theme: readthedocs
site_dir: '../../site'

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_root_heading: true
    watch:
      - .

markdown_extensions:
- markdown_katex
- pymdownx.highlight
- pymdownx.superfences
- admonition

extra_css:
- style.css
extra_javascript: 
- extra.js