
export { vid1Type, res1Type, hist1Type }

const vid1 = {
  group_id: 0,
  type_id: 36,
  type_id_1: 35,
  type_name: "电影解说",
  vod_actor: "",
  vod_area: "大陆",
  vod_author: "",
  vod_behind: "",
  vod_blurb: "说电影《无懈可击之美女如云》",
  vod_class: "电影解说",
  vod_color: "",
  vod_content: "说电影《无懈可击之美女如云》",
  vod_copyright: 0,
  vod_director: "",
  vod_douban_id: 0,
  vod_douban_score: "0.0",
  vod_down: 0,
  vod_down_from: "xunlei",
  vod_down_note: "",
  vod_down_server: "no",
  vod_down_url: "全集$http://okxxxzy.xzokzyzy.com/20210118/9445_ca072f2c/无懈可击之美女如云2010中国.mp4",
  vod_duration: "",
  vod_en: "shuodianyingwuxiekejizhimeinvruyun",
  vod_hits: 0,
  vod_hits_day: 0,
  vod_hits_month: 0,
  vod_hits_week: 0,
  vod_id: 67495,
  vod_isend: 1,
  vod_jumpurl: "",
  vod_lang: "汉语普通话",
  vod_letter: "S",
  vod_level: 0,
  vod_lock: 0,
  vod_name: "说电影《无懈可击之美女如云》",
  vod_pic: "https://images.cnblogsc.com/pic/upload/vod/2021-01/202101191611020377.jpg",
  vod_pic_slide: "",
  vod_pic_thumb: "",
  vod_play_from: "kuyun$$$ckm3u8",
  vod_play_note: "$$$",
  vod_play_server: "no$$$no",
  vod_play_url: "全集$https://good.jieshuo-okzy.com/share/f74412c3c1c8899f3c130bb30ed0e363$$$全集$https://good.jieshuo-okzy.com/20210118/9445_ca072f2c/index.m3u8",
  vod_points: 0,
  vod_points_down: 0,
  vod_points_play: 0,
  vod_pubdate: "",
  vod_pwd: "",
  vod_pwd_down: "",
  vod_pwd_down_url: "",
  vod_pwd_play: "",
  vod_pwd_play_url: "",
  vod_pwd_url: "",
  vod_rel_art: "",
  vod_rel_vod: "",
  vod_remarks: "",
  vod_reurl: "",
  vod_score: "0.0",
  vod_score_all: 0,
  vod_score_num: 0,
  vod_serial: "0",
  vod_state: "",
  vod_status: 1,
  vod_sub: "",
  vod_tag: "",
  vod_time: "2021-01-21 00:00:04",
  vod_time_add: 1611020523,
  vod_time_hits: 0,
  vod_time_make: 0,
  vod_total: 0,
  vod_tpl: "",
  vod_tpl_down: "",
  vod_tpl_play: "",
  vod_trysee: 0,
  vod_tv: "",
  vod_up: 0,
  vod_version: "",
  vod_weekday: "",
  vod_writer: "",
  vod_year: "2010",
}

const res1 = {
  code: 1,
  limit: "25",
  list: [vid1],
  msg: "数据列表",
  page: 1,
  pagecount: 47,
  total: 1171,
}

type vid1Type = typeof vid1
type res1Type = typeof res1
type hist1Type = {
  vidID: number | string, 
  ij: number[],
  prog : number,
  info : string,
}